import type { Metadata } from "next";
import { headers } from "next/headers";
import { Lora, IBM_Plex_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { locales, defaultLocale, type Locale } from "@/lib/i18n";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-serif",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const localeHeader = headersList.get("x-next-locale");
  const lang: Locale =
    localeHeader && (locales as readonly string[]).includes(localeHeader)
      ? (localeHeader as Locale)
      : defaultLocale;

  return (
    <html lang={lang} className="light" suppressHydrationWarning>
      <body
        className={`${plusJakarta.variable} ${lora.variable} ${ibmPlexMono.variable} font-sans antialiased`}
      >
        <div className="bg-ambient-layer" aria-hidden="true" />
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
